name: ws_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  shelf_plus: ^1.2.2

dev_dependencies:
  lints: ^1.0.0
